### Create Customer
POST http://localhost:5193/Customers
Content-Type: application/json

{
  "name": "Joebodgfhsfb",
  "address": "123 Ave",
  "phone": "5553622",
  "email": "hello@somewsfdghshhere.net2"
}

### Get Customers
GET http://localhost:5193/Customers

### Update Customers
PUT http://localhost:5193/Customers/11
Content-Type: application/json

{
  "id": 11,
  "name": "saedfhg",
  "address": "123 Main St",
  "phone": "555-1234",
  "email": "johntrh.doe@example.comeee"
}

### Delete Customer
DELETE http://localhost:5193/Customers/11

### Get all customers with orders
GET http://localhost:5193/customers/customer-orders

### Add Order to Customer
POST http://localhost:5193/customers/3/orders
Content-Type: application/json

{
  "id": 4,
  "product": "Paper",
  "quantity": 100,
  "price": 50.0,
  "orderDate": "2024-09-27T00:00:00Z",
  "status": "Pending"
}

### Create OrderEntry
POST http://localhost:5193/orderentries
Content-Type: application/json

{
  "quantity": 10,
  "productId": null,
  "orderId": null
}

### Get All OrderEntries
GET http://localhost:5193/orderentries

### Get OrderEntries by Order ID
GET http://localhost:5193/orderentries/order/1

### Get OrderEntries by Product ID
GET http://localhost:5193/orderentries/product/1

### Update OrderEntry
PUT http://localhost:5193/orderentries/1
Content-Type: application/json

{
  "quantity": 20,
  "productId": 1,
  "orderId": 1
}

### Delete OrderEntry
DELETE http://localhost:5193/orderentries/1

### Add a New Paper
POST http://localhost:5193/paper
Content-Type: application/json

{
  "name": "Some Special Paper4444",
  "discontinued": false,
  "stock": 100,
  "price": 5.99
}

### Get All Papers
GET http://localhost:5193/paper

### Get Paper by ID
GET http://localhost:5193/paper/2

### Get Papers by Property ID
GET http://localhost:5193/paper/property/2

### Update Paper
PUT http://localhost:5193/paper/4
Content-Type: application/json

{
  "id": 4,
  "name": "NSpecial",
  "discontinued": false,
  "stock": 150,
  "price": 6.99
}

### Delete Paper
DELETE http://localhost:5193/paper/1

### Create Properties
POST http://localhost:5193/properties
Content-Type: application/json

{
  "propertyName": "last property"
}

### Get Properties
GET http://localhost:5193/properties

### Update Properties
PUT http://localhost:5193/properties/4
Content-Type: application/json

{
  "id": 4,
  "propertyName": "hello"
}

### Delete Properties
DELETE http://localhost:5193/properties/4

### Create an Order
POST http://localhost:5193/orders
Content-Type: application/json

{
  "orderDate": "2024-09-27T00:00:00Z",
  "deliveryDate": null,
  "status": "Pending",
  "totalAmount": 100.0,
  "customerId": 4
}

### Get All Orders
GET http://localhost:5193/orders

### Get Order by ID
GET http://localhost:5193/orders/3

### Get Orders by Customer ID
GET http://localhost:5193/orders/customer/3

### Update Order
PUT http://localhost:5193/orders/21
Content-Type: application/json

{
  "id": 21,
  "orderDate": "2024-09-27T00:00:00Z",
  "deliveryDate": "2024-10-01",
  "status": "Finished",
  "totalAmount": 100.0,
  "customerId": 7
}

### Delete Order
DELETE http://localhost:5193/orders/3