name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          
      - name: Restore dependencies for API
        run: dotnet restore server/API/API.csproj

      - name: Restore dependencies for Tests
        run: dotnet restore server/DundlerMifflinWebApp.Tests/DundlerMifflinWebApp.Tests.csproj

      - name: Build API
        run: dotnet build server/API/API.csproj --no-restore

      - name: Build Tests
        run: dotnet build server/DundlerMifflinWebApp.Tests/DundlerMifflinWebApp.Tests.csproj --no-restore

      - name: Run tests
        run: dotnet test server/DundlerMifflinWebApp.Tests/DundlerMifflinWebApp.Tests.csproj --no-build --verbosity normal
        
      - name: Install Dependencies for front-end
        run: npm install
        working-directory: client
        
      - name: Build front-end
        run: npm run build
        working-directory: client
